{% set name = "duplicity" %}
{% set version = "0.8.18" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duplicity-{{ version }}.tar.gz
  sha256: 6664424e52f8b9abd94ce1a1ef2a5e373877e23030f515dde91ab424d3d456e1

build:
  number: 0
  skip: true  # [py>=40 or py2k or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - librsync
  run:
    - librsync
    - fasteners
    - future
    - python

test:
  imports:
    - duplicity
    - duplicity.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://duplicity.nongnu.org/index.html
  summary: Encrypted backup using rsync algorithm
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: http://duplicity.nongnu.org/
  dev_url: https://gitlab.com/duplicity/duplicity/

extra:
  recipe-maintainers:
    - kpalin
