{% set name = "duplicity" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duplicity-{{ version }}.tar.gz
  sha256: bd3c8a5ad3cf9d2709540806b03d7186f9e4473d922bea6051248a2acc7ecf0f

build:
  number: 0
  skip: true  # [py>=40 or py2k or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - librsync
  run:
    - librsync
    - fasteners
    - future
    - python

test:
  imports:
    - duplicity
    - duplicity.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://duplicity.nongnu.org/index.html
  summary: Encrypted backup using rsync algorithm
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: http://duplicity.nongnu.org/
  dev_url: https://gitlab.com/duplicity/duplicity/

extra:
  recipe-maintainers:
    - kpalin
