{% set name = "duplicity" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/duplicity-{{ version }}.tar.gz
  sha256: 24b4d8af0d167d0498c3c9d7ce4151db08f6b3175a3e295eeccfe42915b1fe90

build:
  number: 0
  skip: true  # [py>=40 or py2k or win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - librsync
  run:
    - librsync
    - fasteners
    - future
    - python

test:
  imports:
    - duplicity
    - duplicity.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://duplicity.nongnu.org/index.html
  summary: Encrypted backup using rsync algorithm
  license: GPL-2.0-or-later
  license_file: COPYING
  doc_url: http://duplicity.nongnu.org/
  dev_url: https://gitlab.com/duplicity/duplicity/

extra:
  recipe-maintainers:
    - kpalin
